name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:latest  # Uses a prebuilt R environment with Quarto

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install missing R packages
      - name: Install R Packages
        run: |
          Rscript -e "needed <- c('rmarkdown', 'tidyverse', 'quarto', 'leaflet');
                      installed <- rownames(installed.packages());
                      to_install <- setdiff(needed, installed);
                      if (length(to_install) > 0) install.packages(to_install)"

      - name: Render Quarto Project
        run: quarto render
        
      - name: Copy Code Files to Deployment Directory
        run: cp -r code _book/code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './_book'